# Configurações de Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_restaurante
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true