CREATE DATABASE "delivery_restaurante";

CREATE TYPE TipoAuditoria AS ENUM ('ENTRADA', 'SAIDA', 'AJUSTE');
CREATE TYPE TipoUnidade AS ENUM ('KG', 'G', 'ML', 'L', 'UN');
CREATE TYPE TipoPagamentoMetodo AS ENUM ('PIX', 'CARTAO', 'DINHEIRO');
CREATE TYPE TipoPagamentoStatus AS ENUM ('PENDENTE', 'APROVADO', 'REJEITADO');
CREATE TYPE TipoPedidoStatus AS ENUM ('CRIADO', 'EM_PROCESSAMENTO', 'CANCELADO', 'CONCLUIDO');
CREATE TYPE TipoProducaoStatus AS ENUM ('FEITO', 'FAZENDO', 'PARADO');
CREATE TYPE TipoEntregaStatus AS ENUM ('PREPARANDO', 'EM_ROTA', 'ENTREGUE', 'FALHA_ENTREGA');

CREATE TABLE Funcionario (
    id_funcionario INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    salario DECIMAL(10,2) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    telefone VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_funcionario PRIMARY KEY (id_funcionario),
    CONSTRAINT uq_funcionario_cpf UNIQUE (cpf),
    CONSTRAINT uq_funcionario_telefone UNIQUE (telefone),
    CONSTRAINT ck_funcionario_salario_positivo CHECK (salario >= 0)
);

CREATE TABLE CategoriaProduto (
    id_categoria INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categoriaproduto PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoriaproduto_nome UNIQUE (nome)
);

CREATE TABLE Produto (
    id_produto INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_categoria INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    unidade_medida TipoUnidade,
    estoque_atual INT,
    preco_venda DECIMAL(10,2),
    descricao VARCHAR(255),
    CONSTRAINT pk_produto PRIMARY KEY (id_produto),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES CategoriaProduto(id_categoria),
    CONSTRAINT ck_produto_estoque_nao_negativo CHECK (estoque_atual >= 0),
    CONSTRAINT ck_produto_preco_positivo CHECK (preco_venda >= 0)
);

CREATE TABLE Insumo (
    id_insumo INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    unidade_medida TipoUnidade,
    estoque_atual INT,
    perecivel BOOLEAN,
    data_validade DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_insumo PRIMARY KEY (id_insumo),
    CONSTRAINT ck_insumo_estoque_nao_negativo CHECK (estoque_atual >= 0)
);

CREATE TABLE Cliente (
    id_cliente INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(100),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_cpf UNIQUE (cpf),
    CONSTRAINT uq_cliente_email UNIQUE (email)
);

CREATE TABLE Endereco (
    id_endereco INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    rua VARCHAR(150),
    numero VARCHAR(10),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    cep VARCHAR(8),
    complemento VARCHAR(100),
    CONSTRAINT pk_endereco PRIMARY KEY (id_endereco),
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
    CONSTRAINT uq_endereco_cliente UNIQUE (id_cliente)
);

CREATE TABLE Pagamento (
    id_pagamento INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metodo_pagamento TipoPagamentoMetodo,
    status_pagamento TipoPagamentoStatus,
    data_pagamento TIMESTAMP,
    CONSTRAINT pk_pagamento PRIMARY KEY (id_pagamento)
);

CREATE TABLE AuditoriaEstoqueProduto (
    id_auditoria_estoque INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_produto INT NOT NULL,
    tipo_movimento TipoAuditoria NOT NULL,
    quantidade INT NOT NULL,
    data TIMESTAMP NOT NULL,
    motivo TEXT,
    CONSTRAINT pk_auditoriaestoqueproduto PRIMARY KEY (id_auditoria_estoque),
    CONSTRAINT fk_auditoriaestoqueproduto_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto),
    CONSTRAINT ck_auditoriaestoqueproduto_quantidade_positiva CHECK (quantidade > 0)
);

CREATE TABLE Fornecedor (
    id_fornecedor INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cnpj CHAR(14) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    CONSTRAINT pk_fornecedor PRIMARY KEY (id_fornecedor),
    CONSTRAINT uq_fornecedor_cnpj UNIQUE (cnpj)
);

CREATE TABLE NotaFiscal (
    id_nota_fiscal INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor INT NOT NULL,
    id_pagamento INT,
    data_nota_fiscal TIMESTAMP NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscal PRIMARY KEY (id_nota_fiscal),
    CONSTRAINT fk_notafiscal_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES Fornecedor(id_fornecedor),
    CONSTRAINT fk_notafiscal_pagamento FOREIGN KEY (id_pagamento) REFERENCES Pagamento(id_pagamento),
    CONSTRAINT ck_notafiscal_valor_positivo CHECK (valor_total >= 0)
);

CREATE TABLE NotaFiscalProduto (
    id_nota_fiscal INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade_produto INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscalproduto PRIMARY KEY (id_nota_fiscal, id_produto),
    CONSTRAINT fk_notafiscalproduto_notafiscal FOREIGN KEY (id_nota_fiscal) REFERENCES NotaFiscal(id_nota_fiscal),
    CONSTRAINT fk_notafiscalproduto_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto)
);

CREATE TABLE NotaFiscalInsumo (
    id_nota_fiscal INT NOT NULL,
    id_insumo INT NOT NULL,
    quantidade_insumo INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscalinsumo PRIMARY KEY (id_nota_fiscal, id_insumo),
    CONSTRAINT fk_notafiscalinsumo_notafiscal FOREIGN KEY (id_nota_fiscal) REFERENCES NotaFiscal(id_nota_fiscal),
    CONSTRAINT fk_notafiscalinsumo_insumo FOREIGN KEY (id_insumo) REFERENCES Insumo(id_insumo)
);

CREATE TABLE Pedido (
    id_pedido INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_pagamento INT NOT NULL,
    id_funcionario INT NOT NULL,
    data_pedido TIMESTAMP NOT NULL,
    status_pedido TipoPedidoStatus NOT NULL,
    total_pedido DECIMAL(10,2) NOT NULL,
    observacao VARCHAR(255),
    taxa_entrega DECIMAL(10,2),
    valor_itens DECIMAL(10,2),
    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
    CONSTRAINT fk_pedido_pagamento FOREIGN KEY (id_pagamento) REFERENCES Pagamento(id_pagamento),
    CONSTRAINT fk_pedido_funcionario FOREIGN KEY (id_funcionario) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT ck_pedido_total_positivo CHECK (total_pedido >= 0)
);

CREATE TABLE Entrega (
    id_entrega INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_funcionario_entrega INT NOT NULL,
    id_pedido INT NOT NULL,
    previsao_entrega TIMESTAMP,
    status_entrega TipoEntregaStatus,
    observacoes_entrega TEXT,
    CONSTRAINT pk_entrega PRIMARY KEY (id_entrega),
    CONSTRAINT fk_entrega_funcionario FOREIGN KEY (id_funcionario_entrega) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT fk_entrega_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido),
    CONSTRAINT uq_entrega_pedido UNIQUE (id_pedido)
);

CREATE TABLE ItemPedido (
    id_produto INT NOT NULL,
    id_pedido INT NOT NULL,
    quantidade INT NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    CONSTRAINT pk_itempedido PRIMARY KEY (id_produto, id_pedido),
    CONSTRAINT fk_itempedido_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto),
    CONSTRAINT fk_itempedido_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido),
    CONSTRAINT ck_itempedido_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_itempedido_preco_positivo CHECK (preco >= 0)
);

CREATE TABLE Producao (
    id_producao INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_produto_fabricado INT NOT NULL,
    id_funcionario INT,
    quantidade_planejada INT NOT NULL,
    quantidade_real INT,
    status_producao TipoProducaoStatus NOT NULL,
    CONSTRAINT pk_producao PRIMARY KEY (id_producao),
    CONSTRAINT fk_producao_produto FOREIGN KEY (id_produto_fabricado) REFERENCES Produto(id_produto),
    CONSTRAINT fk_producao_funcionario FOREIGN KEY (id_funcionario) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT ck_producao_planejada_positiva CHECK (quantidade_planejada > 0)
);

CREATE TABLE ItemInsumo (
    id_insumo INT NOT NULL,
    id_producao INT NOT NULL,
    quantidade INT NOT NULL,
    CONSTRAINT pk_iteminsumo PRIMARY KEY (id_insumo, id_producao),
    CONSTRAINT fk_iteminsumo_insumo FOREIGN KEY (id_insumo) REFERENCES Insumo(id_insumo),
    CONSTRAINT fk_iteminsumo_producao FOREIGN KEY (id_producao) REFERENCES Producao(id_producao),
    CONSTRAINT ck_iteminsumo_quantidade_positiva CHECK (quantidade > 0)
);