CREATE TYPE TipoAuditoria AS ENUM ('ENTRADA', 'SAIDA', 'AJUSTE');
CREATE TYPE TipoUnidade AS ENUM ('KG', 'G', 'ML', 'L', 'UN');
CREATE TYPE TipoPagamentoMetodo AS ENUM ('PIX', 'CARTAO', 'DINHEIRO');
CREATE TYPE TipoPagamentoStatus AS ENUM ('PENDENTE', 'APROVADO', 'REJEITADO');
CREATE TYPE TipoPedidoStatus AS ENUM ('CRIADO', 'EM_PROCESSAMENTO', 'CANCELADO', 'CONCLUIDO');
CREATE TYPE TipoProducaoStatus AS ENUM ('FEITO', 'FAZENDO', 'PARADO');
CREATE TYPE TipoEntregaStatus AS ENUM ('PREPARANDO', 'EM_ROTA', 'ENTREGUE', 'FALHA_ENTREGA');

CREATE TABLE Funcionario (
    id_funcionario INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    salario DECIMAL(10,2) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    telefone VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_funcionario PRIMARY KEY (id_funcionario),
    CONSTRAINT uq_funcionario_cpf UNIQUE (cpf),
    CONSTRAINT uq_funcionario_telefone UNIQUE (telefone),
    CONSTRAINT ck_funcionario_salario_positivo CHECK (salario >= 0)
);

CREATE TABLE CategoriaProduto (
    id_categoria INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categoriaproduto PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoriaproduto_nome UNIQUE (nome)
);

CREATE TABLE Produto (
    id_produto INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_categoria INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    unidade_medida TipoUnidade,
    estoque_atual INT,
    preco_venda DECIMAL(10,2),
    descricao VARCHAR(255),
    CONSTRAINT pk_produto PRIMARY KEY (id_produto),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES CategoriaProduto(id_categoria),
    CONSTRAINT ck_produto_estoque_nao_negativo CHECK (estoque_atual >= 0),
    CONSTRAINT ck_produto_preco_positivo CHECK (preco_venda >= 0)
);

CREATE TABLE Insumo (
    id_insumo INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    unidade_medida TipoUnidade,
    estoque_atual INT,
    perecivel BOOLEAN,
    data_validade DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_insumo PRIMARY KEY (id_insumo),
    CONSTRAINT ck_insumo_estoque_nao_negativo CHECK (estoque_atual >= 0)
);

CREATE TABLE Cliente (
    id_cliente INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(100),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_cpf UNIQUE (cpf),
    CONSTRAINT uq_cliente_email UNIQUE (email)
);

CREATE TABLE Endereco (
    id_endereco INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    rua VARCHAR(150),
    numero VARCHAR(10),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    cep VARCHAR(8),
    complemento VARCHAR(100),
    CONSTRAINT pk_endereco PRIMARY KEY (id_endereco),
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
    CONSTRAINT uq_endereco_cliente UNIQUE (id_cliente)
);

CREATE TABLE Pagamento (
    id_pagamento INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metodo_pagamento TipoPagamentoMetodo,
    status_pagamento TipoPagamentoStatus,
    data_pagamento TIMESTAMP,
    CONSTRAINT pk_pagamento PRIMARY KEY (id_pagamento)
);

CREATE TABLE AuditoriaEstoqueProduto (
    id_auditoria_estoque INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_produto INT NOT NULL,
    tipo_movimento TipoAuditoria NOT NULL,
    quantidade INT NOT NULL,
    data TIMESTAMP NOT NULL,
    motivo TEXT,
    CONSTRAINT pk_auditoriaestoqueproduto PRIMARY KEY (id_auditoria_estoque),
    CONSTRAINT fk_auditoriaestoqueproduto_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto),
    CONSTRAINT ck_auditoriaestoqueproduto_quantidade_positiva CHECK (quantidade > 0)
);

CREATE TABLE Fornecedor (
    id_fornecedor INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cnpj CHAR(14) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    CONSTRAINT pk_fornecedor PRIMARY KEY (id_fornecedor),
    CONSTRAINT uq_fornecedor_cnpj UNIQUE (cnpj)
);

CREATE TABLE NotaFiscal (
    id_nota_fiscal INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor INT NOT NULL,
    id_pagamento INT,
    data_nota_fiscal TIMESTAMP NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscal PRIMARY KEY (id_nota_fiscal),
    CONSTRAINT fk_notafiscal_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES Fornecedor(id_fornecedor),
    CONSTRAINT fk_notafiscal_pagamento FOREIGN KEY (id_pagamento) REFERENCES Pagamento(id_pagamento),
    CONSTRAINT ck_notafiscal_valor_positivo CHECK (valor_total >= 0)
);

CREATE TABLE NotaFiscalProduto (
    id_nota_fiscal INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade_produto INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscalproduto PRIMARY KEY (id_nota_fiscal, id_produto),
    CONSTRAINT fk_notafiscalproduto_notafiscal FOREIGN KEY (id_nota_fiscal) REFERENCES NotaFiscal(id_nota_fiscal),
    CONSTRAINT fk_notafiscalproduto_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto)
);

CREATE TABLE NotaFiscalInsumo (
    id_nota_fiscal INT NOT NULL,
    id_insumo INT NOT NULL,
    quantidade_insumo INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_notafiscalinsumo PRIMARY KEY (id_nota_fiscal, id_insumo),
    CONSTRAINT fk_notafiscalinsumo_notafiscal FOREIGN KEY (id_nota_fiscal) REFERENCES NotaFiscal(id_nota_fiscal),
    CONSTRAINT fk_notafiscalinsumo_insumo FOREIGN KEY (id_insumo) REFERENCES Insumo(id_insumo)
);

CREATE TABLE Pedido (
    id_pedido INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_pagamento INT NOT NULL,
    id_funcionario INT NOT NULL,
    data_pedido TIMESTAMP NOT NULL,
    status_pedido TipoPedidoStatus NOT NULL,
    total_pedido DECIMAL(10,2) NOT NULL,
    observacao VARCHAR(255),
    taxa_entrega DECIMAL(10,2),
    valor_itens DECIMAL(10,2),
    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
    CONSTRAINT fk_pedido_pagamento FOREIGN KEY (id_pagamento) REFERENCES Pagamento(id_pagamento),
    CONSTRAINT fk_pedido_funcionario FOREIGN KEY (id_funcionario) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT ck_pedido_total_positivo CHECK (total_pedido >= 0)
);

CREATE TABLE Entrega (
    id_entrega INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_funcionario_entrega INT NOT NULL,
    id_pedido INT NOT NULL,
    previsao_entrega TIMESTAMP,
    status_entrega TipoEntregaStatus,
    observacoes_entrega TEXT,
    CONSTRAINT pk_entrega PRIMARY KEY (id_entrega),
    CONSTRAINT fk_entrega_funcionario FOREIGN KEY (id_funcionario_entrega) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT fk_entrega_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido),
    CONSTRAINT uq_entrega_pedido UNIQUE (id_pedido)
);

CREATE TABLE ItemPedido (
    id_produto INT NOT NULL,
    id_pedido INT NOT NULL,
    quantidade INT NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    CONSTRAINT pk_itempedido PRIMARY KEY (id_produto, id_pedido),
    CONSTRAINT fk_itempedido_produto FOREIGN KEY (id_produto) REFERENCES Produto(id_produto),
    CONSTRAINT fk_itempedido_pedido FOREIGN KEY (id_pedido) REFERENCES Pedido(id_pedido),
    CONSTRAINT ck_itempedido_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_itempedido_preco_positivo CHECK (preco >= 0)
);

CREATE TABLE Producao (
    id_producao INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_produto_fabricado INT NOT NULL,
    id_funcionario INT,
    quantidade_planejada INT NOT NULL,
    quantidade_real INT,
    status_producao TipoProducaoStatus NOT NULL,
    CONSTRAINT pk_producao PRIMARY KEY (id_producao),
    CONSTRAINT fk_producao_produto FOREIGN KEY (id_produto_fabricado) REFERENCES Produto(id_produto),
    CONSTRAINT fk_producao_funcionario FOREIGN KEY (id_funcionario) REFERENCES Funcionario(id_funcionario),
    CONSTRAINT ck_producao_planejada_positiva CHECK (quantidade_planejada > 0)
);

CREATE TABLE ItemInsumo (
    id_insumo INT NOT NULL,
    id_producao INT NOT NULL,
    quantidade INT NOT NULL,
    CONSTRAINT pk_iteminsumo PRIMARY KEY (id_insumo, id_producao),
    CONSTRAINT fk_iteminsumo_insumo FOREIGN KEY (id_insumo) REFERENCES Insumo(id_insumo),
    CONSTRAINT fk_iteminsumo_producao FOREIGN KEY (id_producao) REFERENCES Producao(id_producao),
    CONSTRAINT ck_iteminsumo_quantidade_positiva CHECK (quantidade > 0)
);


-- Trigger de validação da data de insumo

CREATE OR REPLACE FUNCTION fn_validar_data_insumo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.data_validade < CURRENT_DATE AND NEW.data_validade IS NOT NULL THEN
        RAISE EXCEPTION 'ERRO: O insumo "%" não pode ser cadastrado pois está vencido. Validade: %, Hoje: %', 
            NEW.nome, 
            TO_CHAR(NEW.data_validade, 'DD/MM/YYYY'), 
            TO_CHAR(CURRENT_DATE, 'DD/MM/YYYY');
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_antes_inserir_insumo
BEFORE INSERT ON Insumo
FOR EACH ROW
EXECUTE FUNCTION fn_validar_data_insumo();

---

INSERT INTO Funcionario (id_funcionario, nome, cpf, salario, cargo, telefone) VALUES
(1, 'Joana Silva', '11111111111', 3000.00, 'Entregadora', '999999999'),
(2, 'Carlos Souza', '22222222222', 4500.00, 'Gerente de Produção', '888888888'),
(3, 'Pedro Álvares', '33333333333', 3200.00, 'Cozinheiro Chefe', '777777777'),
(4, 'Ana Luiza', '44444444444', 2800.00, 'Atendente', '666666666'),
(5, 'Ricardo Martins', '55555555555', 3100.00, 'Entregador', '555555555'),
(6, 'Fernanda Costa', '66666666666', 4800.00, 'Gerente de Vendas', '444444444'),
(7, 'Gabriel Lima', '77777777777', 3500.00, 'Cozinheiro', '333333333'),
(8, 'Beatriz Santos', '88888888888', 2900.00, 'Atendente', '222222222'),
(9, 'Fábio Melo', '99999999999', 3000.00, 'Entregador', '111111111'),
(10, 'Lara Rezende', '10101010101', 3300.00, 'Supervisor de Estoque', '101010101');

INSERT INTO CategoriaProduto (id_categoria, nome, descricao) VALUES
(1, 'Bebidas', 'Refrigerantes, sucos e águas.'),
(2, 'Lanches', 'Hambúrgueres e sanduíches.'),
(3, 'Ingredientes Base', 'Itens brutos para fabricação.'),
(4, 'Sobremesas', 'Doces e pudins.'),
(5, 'Acompanhamentos', 'Batata frita, anéis de cebola.'),
(6, 'Marmitas', 'Pratos prontos para o almoço.'),
(7, 'Saladas', 'Opções saudáveis.'),
(8, 'Molhos', 'Molhos diversos e temperos.'),
(9, 'Vegan', 'Opções totalmente vegetais.'),
(10, 'Infantil', 'Combos e pratos para crianças.');

INSERT INTO Insumo (id_insumo, nome, unidade_medida, estoque_atual, perecivel, data_validade) VALUES
(10, 'Pão de Hambúrguer', 'UN', 50, TRUE, '2026-12-01'),
(11, 'Carne Moída (Kg)', 'KG', 10, TRUE, '2026-11-15'),
(12, 'Queijo Muçarela', 'KG', 5, TRUE, '2026-12-30'),
(13, 'Alface Americana', 'UN', 0, TRUE, '2026-11-10'),
(14, 'Tomate', 'KG', 0, TRUE, '2026-11-12'),
(15, 'Óleo Vegetal (L)', 'L', 0, FALSE, '2026-06-01'),
(16, 'Açúcar (Kg)', 'KG', 0, FALSE, '2027-01-01'),
(17, 'Farinha de Trigo (Kg)', 'KG', 0, FALSE, '2026-03-01'),
(18, 'Frango (Kg)', 'KG', 0, TRUE, '2026-11-20'),
(19, 'Cebola', 'KG', 0, TRUE, '2026-12-05'),
(20, 'Embalagem Descartável', 'UN', 0, FALSE, '2027-12-31'),
(21, 'Bacon (Kg)', 'KG', 0, TRUE, '2026-12-05'),
(22, 'Feijão (Kg)', 'KG', 0, FALSE, '2026-10-01'),
(23, 'Arroz (Kg)', 'KG', 0, FALSE, '2026-10-01'),
(24, 'Molho Caesar (L)', 'L', 0, TRUE, '2026-12-15'),
(25, 'Leite Condensado (UN)', 'UN', 0, FALSE, '2026-05-01'),
(26, 'Ovos (UN)', 'UN', 0, TRUE, '2026-12-10'),
(27, 'Leite (L)', 'L', 0, TRUE, '2026-12-08'),
(28, 'Sorvete (L)', 'L', 0, TRUE, '2026-01-01'),
(29, 'Brownie Prémix (Kg)', 'KG', 0, FALSE, '2026-03-01'),
(30, 'Nuggets de Frango (Kg)', 'KG', 0, TRUE, '2026-12-20'),
(31, 'Batata Inglesa (Kg)', 'KG', 50, TRUE, '2026-12-15');

INSERT INTO Produto (id_produto, id_categoria, nome, unidade_medida, estoque_atual, preco_venda, descricao) VALUES
(100, 2, 'X-Salada Gourmet', 'UN', 0, 25.00, 'Sanduíche completo com molho especial.'),
(101, 1, 'Refrigerante Cola', 'L', 30, 8.00, 'Refrigerante 2 Litros.'),
(102, 2, 'X-Bacon Simples', 'UN', 0, 22.00, 'Hambúrguer com bacon e queijo.'),
(103, 5, 'Batata Frita Média', 'UN', 0, 12.00, 'Porção de batata frita.'),
(104, 4, 'Pudim de Leite', 'UN', 0, 10.00, 'Clássico pudim de leite condensado.'),
(105, 1, 'Suco de Laranja (L)', 'L', 15, 9.00, 'Suco natural de laranja.'),
(106, 6, 'Marmita Frango Grelhado', 'UN', 0, 35.00, 'Frango, arroz, feijão e salada.'),
(107, 7, 'Salada Caesar', 'UN', 0, 28.00, 'Salada com croutons e molho Caesar.'),
(108, 2, 'Burger Vegano', 'UN', 0, 30.00, 'Hambúrguer de grão de bico.'),
(109, 1, 'Água Mineral', 'UN', 50, 4.00, 'Água sem gás 500ml.'),
(110, 2, 'X-Frango Crocante', 'UN', 0, 24.00, 'Sanduíche de frango empanado com maionese da casa.'),
(111, 5, 'Onion Rings Média', 'UN', 0, 14.00, 'Anéis de cebola empanados.'),
(112, 1, 'Suco de Maracujá (L)', 'L', 18, 9.00, 'Suco natural de maracujá.'),
(113, 4, 'Mousse de Maracujá', 'UN', 6, 8.00, 'Sobremesa cremosa de maracujá.'),
(114, 6, 'Marmita Bovina Acebolada', 'UN', 0, 38.00, 'Carne bovina acebolada, arroz, feijão e salada.'),
(115, 7, 'Salada Mediterrânea', 'UN', 0, 30.00, 'Salada com tomate, queijo branco, azeite e ervas.'),
(116, 2, 'X-Tudo Premium', 'UN', 0, 32.00, 'Hambúrguer completo com bacon, ovo e molho especial.'),
(117, 1, 'Chá Gelado Limão', 'L', 20, 7.00, 'Chá gelado sabor limão.'),
(118, 5, 'Batata Frita Grande', 'UN', 0, 16.00, 'Porção grande de batata frita crocante.'),
(119, 4, 'Brownie com Sorvete', 'UN', 4, 15.00, 'Brownie quente com bola de sorvete.'),
(120, 2, 'X-Picanha Artesanal', 'UN', 0, 36.00, 'Hambúrguer de picanha com queijo e molho da casa.'),
(121, 6, 'Marmita Vegetariana', 'UN', 0, 33.00, 'Legumes salteados, arroz, feijão e salada.'),
(122, 1, 'Refrigerante Guaraná', 'L', 25, 8.00, 'Garrafa de 2 Litros.'),
(123, 7, 'Salada Tropical', 'UN', 0, 27.00, 'Salada com frutas, folhas verdes e molho leve.'),
(124, 5, 'Porção de Nuggets', 'UN', 0, 13.00, 'Porção de nuggets de frango.'),
(125, 4, 'Torta de Limão', 'UN', 0, 12.00, 'Torta de limão com base crocante.'); 

INSERT INTO Cliente (id_cliente, nome, cpf, email, telefone) VALUES
(50, 'Maria Oliveira', '33333333333', 'maria@email.com', '777777777'),
(51, 'João Pereira', '12312312312', 'joao@email.com', '121212121'),
(52, 'Amanda Rocha', '45645645645', 'amanda@email.com', '343434343'),
(53, 'Roberto Farias', '78978978978', 'roberto@email.com', '565656565'),
(54, 'Luciana Gomes', '98765432198', 'luciana@email.com', '787878787'),
(55, 'Marcos Vinícius', '65432198765', 'marcos@email.com', '909090909'),
(56, 'Carla Prado', '32165498732', 'carla@email.com', '131313131'),
(57, 'Daniel Alves', '14725836914', 'daniel@email.com', '242424242'),
(58, 'Elisa Nogueira', '36925814736', 'elisa@email.com', '353535353'),
(59, 'Felipe Castro', '25836914725', 'felipe@email.com', '464646464');

INSERT INTO Endereco (id_endereco, id_cliente, rua, numero, bairro, cidade, cep, complemento) VALUES
(500, 50, 'Rua das Flores', '15A', 'Centro', 'Cidade Modelo', '58000000', NULL),
(501, 51, 'Avenida Principal', '100', 'Bairro Novo', 'Cidade Modelo', '58000001', 'Apto 101'),
(502, 52, 'Rua da Paz', '22', 'Jardim', 'Cidade Modelo', '58000002', NULL),
(503, 53, 'Travessa das Acácias', '55', 'Industrial', 'Cidade Modelo', '58000003', 'Casa 2'),
(504, 54, 'Estrada Velha', '1200', 'Zona Rural', 'Cidade Modelo', '58000004', 'Sítio'),
(505, 55, 'Rua do Comércio', '300', 'Centro', 'Cidade Modelo', '58000005', 'Loja B'),
(506, 56, 'Alameda dos Pássaros', '45', 'Vila Rica', 'Cidade Modelo', '58000006', NULL),
(507, 57, 'Praça da Liberdade', '1', 'Praça', 'Cidade Modelo', '58000007', 'Kiosque'),
(508, 58, 'Rua Sete', '77', 'Setor Oeste', 'Cidade Modelo', '58000008', 'Bloco C'),
(509, 59, 'Rua Quinze', '15', 'Norte', 'Cidade Modelo', '58000009', 'Fundos');

INSERT INTO Fornecedor (id_fornecedor, nome, cnpj, descricao) VALUES
(1000, 'Distribuidora Alimentos A', '44444444000144', 'Pães e Laticínios.'),
(1001, 'Carnes Premium Ltda', '11111111000111', 'Carnes e derivados.'),
(1002, 'Bebidas e Cia', '22222222000122', 'Refrigerantes e sucos prontos.'),
(1003, 'Hortifruti Fresco', '33333333000133', 'Frutas, legumes e verduras.'),
(1004, 'Embalagens TOP', '55555555000155', 'Embalagens e descartáveis.'),
(1005, 'Grãos Essenciais', '66666666000166', 'Farinhas e açúcares.'),
(1006, 'Laticínios da Serra', '77777777000177', 'Queijos e derivados frescos.'),
(1007, 'Delivery SUPORTE', '88888888000188', 'Serviços de manutenção e software.'),
(1008, 'Frangos Nobres', '99999999000199', 'Produtos de frango e aves.'),
(1009, 'Temperos do Mundo', '10101010000101', 'Especiarias e condimentos.');

-- Trigger que cadastram a entrada de insumos e produtos e fazem a auditoria de produtos

CREATE OR REPLACE FUNCTION fn_entrada_produto_nf()
RETURNS TRIGGER AS $$
DECLARE
    v_existe INT;
BEGIN
    SELECT 1 INTO v_existe
    FROM Produto
    WHERE id_produto = NEW.id_produto;

    IF NOT FOUND THEN
        RAISE EXCEPTION 
            'Erro ao registrar entrada por NF: Produto com ID % não existe.',
            NEW.id_produto;
    END IF;

    IF NEW.quantidade_produto IS NULL OR NEW.quantidade_produto <= 0 THEN
        RAISE EXCEPTION 
            'Erro ao registrar entrada por NF: quantidade inválida (%).',
            NEW.quantidade_produto;
    END IF;

    UPDATE Produto
    SET estoque_atual = COALESCE(estoque_atual, 0) + NEW.quantidade_produto
    WHERE id_produto = NEW.id_produto;

    INSERT INTO AuditoriaEstoqueProduto (
        id_produto,
        tipo_movimento,
        quantidade,
        data,
        motivo
    ) VALUES (
        NEW.id_produto,
        'ENTRADA',
        NEW.quantidade_produto,
        CURRENT_TIMESTAMP,
        'NF ' || NEW.id_nota_fiscal || ': Entrada de Compra'
    );

    RETURN NEW;

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 
            'Falha ao processar a entrada de produto da NF (ID Produto %, Quantidade %, Erro: %)',
            NEW.id_produto,
            NEW.quantidade_produto,
            SQLERRM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_nfproduto_entrada_estoque
AFTER INSERT ON NotaFiscalProduto
FOR EACH ROW
EXECUTE FUNCTION fn_entrada_produto_nf();

---

CREATE OR REPLACE FUNCTION fn_entrada_insumo_nf()
RETURNS TRIGGER AS $$
DECLARE
    v_existe INT;
BEGIN
    SELECT 1 INTO v_existe
    FROM Insumo
    WHERE id_insumo = NEW.id_insumo;

    IF NOT FOUND THEN
        RAISE EXCEPTION 
            'Erro ao registrar entrada por NF: Insumo com ID % não existe.',
            NEW.id_insumo;
    END IF;

    IF NEW.quantidade_insumo IS NULL OR NEW.quantidade_insumo <= 0 THEN
        RAISE EXCEPTION 
            'Erro ao registrar entrada por NF: quantidade inválida (%).',
            NEW.quantidade_insumo;
    END IF;

    UPDATE Insumo
    SET estoque_atual = COALESCE(estoque_atual, 0) + NEW.quantidade_insumo
    WHERE id_insumo = NEW.id_insumo;

    RETURN NEW;

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 
            'Falha ao processar a entrada de insumo da NF (ID Insumo %, Quantidade %, Erro: %)',
            NEW.id_insumo,
            NEW.quantidade_insumo,
            SQLERRM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_nfinsumo_entrada_estoque
AFTER INSERT ON NotaFiscalInsumo
FOR EACH ROW
EXECUTE FUNCTION fn_entrada_insumo_nf();

---

INSERT INTO Pagamento (id_pagamento, metodo_pagamento, status_pagamento, data_pagamento) VALUES
(200, 'PIX', 'APROVADO', '2025-11-28 10:15:00'),
(201, 'PIX', 'PENDENTE', NULL),
(202, 'CARTAO', 'APROVADO', '2025-11-27 14:30:00'),
(203, 'PIX', 'APROVADO', '2025-11-28 09:50:00'),
(204, 'PIX', 'PENDENTE', NULL),
(205, 'CARTAO', 'APROVADO', '2025-11-26 16:05:00'),
(206, 'PIX', 'APROVADO', '2025-11-28 11:00:00'),
(207, 'PIX', 'PENDENTE', NULL),
(208, 'PIX', 'APROVADO', CURRENT_TIMESTAMP),
(209, 'CARTAO', 'APROVADO', CURRENT_TIMESTAMP),
(210, 'PIX', 'APROVADO', CURRENT_TIMESTAMP),
(211, 'PIX', 'APROVADO', CURRENT_TIMESTAMP);

---

INSERT INTO NotaFiscal (id_nota_fiscal, id_fornecedor, id_pagamento, data_nota_fiscal, valor_total) VALUES
(100, 1000, 200, CURRENT_TIMESTAMP, 550.00), 
(101, 1001, 201, CURRENT_TIMESTAMP, 800.00), 
(102, 1002, 202, CURRENT_TIMESTAMP, 490.00), 
(103, 1003, 203, CURRENT_TIMESTAMP, 425.00), 
(104, 1004, 204, CURRENT_TIMESTAMP, 190.00), 
(105, 1008, 205, CURRENT_TIMESTAMP, 600.00),
(106, 1009, 206, CURRENT_TIMESTAMP, 40.00),
(107, 1002, 207, CURRENT_TIMESTAMP, 650.00),
(108, 1000, 208, CURRENT_TIMESTAMP, 300.00),
(109, 1001, 209, CURRENT_TIMESTAMP, 150.00),
(110, 1002, 210, CURRENT_TIMESTAMP, 120.00),
(111, 1003, 211, CURRENT_TIMESTAMP, 80.00);

-- NF 100
    -- Insumos (Pão, Queijo)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(100, 10, 100, 2.50);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(100, 12, 10, 30.00);

-- NF 101
-- Insumo (Carne)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(101, 11, 20, 40.00);

-- NF 102
-- Produtos (Refrigerante, Suco Laranja)
INSERT INTO NotaFiscalProduto (id_nota_fiscal, id_produto, quantidade_produto, valor_unitario) VALUES 
(102, 101, 50, 5.00);
INSERT INTO NotaFiscalProduto (id_nota_fiscal, id_produto, quantidade_produto, valor_unitario) VALUES 
(102, 105, 40, 6.00);

-- NF 103
-- Insumos (Alface, Tomate, Batata)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(103, 13, 5, 5.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(103, 14, 15, 10.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(103, 21, 50, 5.00);

-- NF 104
-- Insumos (Farinha, Açúcar)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(104, 17, 50, 2.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(104, 16, 30, 3.00);

-- NF 105
-- Insumo (Frango)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(105, 18, 10, 60.00);

-- NF 106
-- Insumo (Cebola)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(106, 19, 8, 5.00);

-- NF 107
-- Insumo (Óleo) e Produto (Água)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(107, 15, 50, 8.00);
INSERT INTO NotaFiscalProduto (id_nota_fiscal, id_produto, quantidade_produto, valor_unitario) VALUES 
(107, 109, 100, 2.50);

-- NF 108
-- Laticínios/Congelados (Leite, Sorvete, Nuggets)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(108, 27, 20, 4.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(108, 28, 5, 20.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(108, 30, 10, 10.00);

-- NF 109
-- Secos (Feijão, Arroz, Brownie Prémix)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(109, 22, 30, 4.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(109, 23, 50, 3.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(109, 29, 5, 12.00);

-- NF 110
-- Molhos e Condensados (Molho Caesar, Leite Condensado)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(110, 22, 10, 10.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(110, 25, 20, 5.00);

-- NF 111
-- Outros (Bacon, Ovos)
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(111, 21, 10, 20.00);
INSERT INTO NotaFiscalInsumo (id_nota_fiscal, id_insumo, quantidade_insumo, valor_unitario) VALUES 
(111, 26, 30, 1.00);

CREATE TYPE InsumoProducao AS (
    id_insumo INT,
    quantidade_por_unidade DECIMAL(10, 4) 
);

-- Procedure de produção de produtos
CREATE OR REPLACE PROCEDURE prc_processar_producao_dinamica(
    p_id_produto_fabricado INT,
    p_id_funcionario INT,
    p_quantidade_planejada INT,
    p_quantidade_real INT, 
    p_lista_insumos InsumoProducao[]
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_producao INT;
    v_motivo_entrada TEXT;
    
    v_registro_insumo InsumoProducao; 
    
    v_quantidade_consumida DECIMAL(10, 4);
    v_quantidade_consumida_int INT;
    
    v_estoque_atual INT;
    v_nome_insumo VARCHAR(255);
    v_nome_produto VARCHAR(100);
BEGIN
    SELECT nome INTO v_nome_produto FROM Produto WHERE id_produto = p_id_produto_fabricado;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Produto com ID % não encontrado.', p_id_produto_fabricado;
    END IF;

    FOREACH v_registro_insumo IN ARRAY p_lista_insumos
    LOOP
        v_quantidade_consumida := p_quantidade_real * v_registro_insumo.quantidade_por_unidade;
        
        IF v_quantidade_consumida > 0 THEN
             v_quantidade_consumida_int := CEIL(v_quantidade_consumida);
        ELSE
             v_quantidade_consumida_int := 0;
        END IF;

        IF v_quantidade_consumida_int = 0 THEN
            CONTINUE; 
        END IF;
        
        SELECT estoque_atual, nome INTO v_estoque_atual, v_nome_insumo 
        FROM Insumo 
        WHERE id_insumo = v_registro_insumo.id_insumo;
        
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Insumo com ID % não encontrado. Produção cancelada.', v_registro_insumo.id_insumo;
        END IF;

        IF v_estoque_atual < v_quantidade_consumida_int THEN
            RAISE EXCEPTION 'ESTOQUE INSUFICIENTE: O insumo "%" (ID %) requer % unidades, mas o estoque atual é de % unidades. Produção cancelada.', 
            v_nome_insumo, v_registro_insumo.id_insumo, v_quantidade_consumida_int, v_estoque_atual;
        END IF;
        
    END LOOP;
    
    INSERT INTO Producao (id_produto_fabricado, id_funcionario, quantidade_planejada, quantidade_real, status_producao)
    VALUES (p_id_produto_fabricado, p_id_funcionario, p_quantidade_planejada, p_quantidade_real, 'FEITO')
    RETURNING id_producao INTO v_id_producao;

    FOREACH v_registro_insumo IN ARRAY p_lista_insumos
    LOOP
        v_quantidade_consumida := p_quantidade_real * v_registro_insumo.quantidade_por_unidade;
        
        IF v_quantidade_consumida > 0 THEN
             v_quantidade_consumida_int := CEIL(v_quantidade_consumida);
        ELSE
             v_quantidade_consumida_int := 0;
        END IF;

        IF v_quantidade_consumida_int = 0 THEN
            CONTINUE; 
        END IF;
        
        INSERT INTO ItemInsumo (id_insumo, id_producao, quantidade) 
        VALUES (v_registro_insumo.id_insumo, v_id_producao, v_quantidade_consumida_int);

        UPDATE Insumo SET estoque_atual = estoque_atual - v_quantidade_consumida_int
        WHERE id_insumo = v_registro_insumo.id_insumo;

    END LOOP;

    v_motivo_entrada := 'Produção concluída de ' || v_nome_produto || ' (ID Prod: ' || v_id_producao || ')';

    UPDATE Produto SET estoque_atual = estoque_atual + p_quantidade_real
    WHERE id_produto = p_id_produto_fabricado;

    INSERT INTO AuditoriaEstoqueProduto (id_produto, tipo_movimento, quantidade, data, motivo)
    VALUES (p_id_produto_fabricado, 'ENTRADA', p_quantidade_real, NOW(), v_motivo_entrada);

END $$;

-- Id do produto, quantidade do produto
CREATE TYPE ItemPedidoInfo_v2 AS (
    id_produto INT,
    quantidade INT
);

-- Procedure: Cria um pagamento inicial com status PENDENTE
CREATE OR REPLACE PROCEDURE inserir_pagamento(
    p_metodo_pagamento TipoPagamentoMetodo,
    OUT v_id_pagamento INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO Pagamento (metodo_pagamento, status_pagamento, data_pagamento) 
    VALUES (p_metodo_pagamento, 'PENDENTE', NULL) 
    RETURNING id_pagamento INTO v_id_pagamento;
END $$;

-- Trigger: Liberar o pedido criado (para status EM_PROCESSAMENTO) quando o pagamento do pedido for alterado
-- Aqui garante que o pedido so vai ser feito se o pagamento for efetuado antes.
CREATE OR REPLACE FUNCTION fn_libera_pedido_por_pagamento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status_pagamento = 'APROVADO' AND OLD.status_pagamento <> 'APROVADO' THEN

    UPDATE Pedido
        SET status_pedido = 'EM_PROCESSAMENTO'
        WHERE id_pagamento = NEW.id_pagamento
        AND status_pedido IN ('CRIADO', 'EM_PROCESSAMENTO');


    ELSIF NEW.status_pagamento = 'REJEITADO' AND OLD.status_pagamento <> 'REJEITADO' THEN
        UPDATE Pedido
        SET status_pedido = 'CANCELADO'
        WHERE id_pagamento = NEW.id_pagamento
        AND status_pedido NOT IN ('CANCELADO', 'CONCLUIDO');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_pagamento_libera_pedido
AFTER UPDATE OF status_pagamento ON Pagamento
FOR EACH ROW
EXECUTE FUNCTION fn_libera_pedido_por_pagamento();

-- Processa novo pedido
    --> Validação do Pagamento
    --> Verificação de Estoque e Cálculo
    --> Criação do Pedido
    --> Processamento dos Itens e Baixa de Estoque
    --> Registro da Entrega
CREATE OR REPLACE PROCEDURE processar_novo_pedido(
    p_id_cliente INT,
    p_metodo_pagamento TipoPagamentoMetodo,
    p_id_funcionario_atendimento INT,
    p_id_funcionario_entrega INT,
    p_taxa_entrega DECIMAL(10, 2),
    p_previsao_entrega INTERVAL,
    p_lista_itens ItemPedidoInfo_v2[],
    OUT p_total_calculado DECIMAL(10, 2),
    OUT p_id_pedido_gerado INT, 
    OUT p_id_pagamento_gerado INT,
    p_observacao VARCHAR DEFAULT NULL
    )
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_entrega INT;
    v_valor_itens DECIMAL(10, 2) := 0.00;
    v_total_pedido DECIMAL(10, 2);
    v_registro_item ItemPedidoInfo_v2;
    v_status_pedido TipoPedidoStatus;
    v_estoque_atual INT;
    v_preco_unitario DECIMAL(10, 2);
    v_status_entrega TipoEntregaStatus := 'PREPARANDO';
BEGIN
    CALL inserir_pagamento(p_metodo_pagamento, p_id_pagamento_gerado);
    
    IF p_id_pagamento_gerado IS NULL THEN
        RAISE EXCEPTION 'Falha ao gerar registro de pagamento.';
    END IF;

    v_status_pedido := 'CRIADO';

    IF p_lista_itens IS NULL OR array_length(p_lista_itens, 1) IS NULL THEN
        RAISE EXCEPTION 'Nenhum item informado para o pedido.';
    END IF;

    FOREACH v_registro_item IN ARRAY p_lista_itens
    LOOP
        SELECT estoque_atual, preco_venda
        INTO v_estoque_atual, v_preco_unitario
        FROM Produto 
        WHERE id_produto = v_registro_item.id_produto;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Produto com ID % não encontrado. Pedido cancelado.',
                v_registro_item.id_produto;
        END IF;

        IF v_registro_item.quantidade <= 0 THEN
             RAISE EXCEPTION 'Quantidade inválida (%). Deve ser maior que zero.',
                v_registro_item.quantidade;
        END IF;

        IF v_estoque_atual < v_registro_item.quantidade THEN
            RAISE EXCEPTION
                'ESTOQUE INSUFICIENTE: Produto % requer %, mas estoque é %.',
                v_registro_item.id_produto,
                v_registro_item.quantidade,
                v_estoque_atual;
        END IF;

        v_valor_itens := v_valor_itens + (v_registro_item.quantidade * v_preco_unitario);
    END LOOP;

    v_total_pedido := v_valor_itens + p_taxa_entrega;
    p_total_calculado := v_total_pedido;

    INSERT INTO Pedido (
        id_cliente,
        id_pagamento,
        id_funcionario,
        data_pedido,
        status_pedido,
        total_pedido,
        valor_itens,
        taxa_entrega,
        observacao
    )
    VALUES (
        p_id_cliente,
        p_id_pagamento_gerado,
        p_id_funcionario_atendimento,
        CURRENT_TIMESTAMP,
        v_status_pedido,
        v_total_pedido,
        v_valor_itens,
        p_taxa_entrega,
        p_observacao
    )
    RETURNING id_pedido INTO p_id_pedido_gerado;

    FOREACH v_registro_item IN ARRAY p_lista_itens
    LOOP
        SELECT preco_venda INTO v_preco_unitario
        FROM Produto
        WHERE id_produto = v_registro_item.id_produto;

        INSERT INTO ItemPedido (id_produto, id_pedido, quantidade, preco)
        VALUES (v_registro_item.id_produto, p_id_pedido_gerado, v_registro_item.quantidade, v_preco_unitario);

        UPDATE Produto
        SET estoque_atual = estoque_atual - v_registro_item.quantidade
        WHERE id_produto = v_registro_item.id_produto;

        INSERT INTO AuditoriaEstoqueProduto (
            id_produto, tipo_movimento, quantidade, data, motivo
        )
        VALUES (
            v_registro_item.id_produto,
            'SAIDA',
            v_registro_item.quantidade,
            CURRENT_TIMESTAMP,
            'Reserva Pedido ID ' || p_id_pedido_gerado || ' (Pagamento PENDENTE)'
        );
    END LOOP;

    INSERT INTO Entrega (
        id_funcionario_entrega,
        id_pedido,
        previsao_entrega,
        status_entrega
    )
    VALUES (
        p_id_funcionario_entrega,
        p_id_pedido_gerado,
        CURRENT_TIMESTAMP + p_previsao_entrega,
        v_status_entrega
    )
    RETURNING id_entrega INTO v_id_entrega;

END $$;

CREATE OR REPLACE FUNCTION fn_calcular_total_pedido(p_id_pedido INT)
RETURNS DECIMAL(10,2)
LANGUAGE plpgsql AS $$
DECLARE
    v_total DECIMAL(10,2);
    v_entrega DECIMAL(10,2);
BEGIN
    SELECT COALESCE(SUM(ip.quantidade * ip.preco), 0)
    INTO v_total
    FROM ItemPedido ip
    WHERE ip.id_pedido = p_id_pedido;

    SELECT COALESCE(taxa_entrega, 0)
    INTO v_entrega
    FROM Pedido
    WHERE id_pedido = p_id_pedido;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    RETURN v_total + v_entrega;
END;
$$;

CREATE OR REPLACE FUNCTION fn_insumos_proximos_validade()
RETURNS NUMERIC AS $$
DECLARE
    total INT;
    proximos INT;
BEGIN
    BEGIN
        SELECT COUNT(*) INTO total FROM Insumo;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END;

    BEGIN
        SELECT COUNT(*) INTO proximos
        FROM Insumo
        WHERE perecivel = TRUE 
        AND data_validade <= CURRENT_DATE + INTERVAL '7 days';
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END;

    IF total = 0 THEN
        RETURN 0;
    END IF;

    RETURN ROUND((proximos::NUMERIC / total::NUMERIC) * 100, 2);
END;
$$ LANGUAGE plpgsql;
